### ISSUE TITLE
The Github icon is almost invisible on the light theme

### ISSUE THREAD

**Issue by henriquebuzon** [bgwebagency/restoreportraits.com#14]
The foreground changes color accordingly to the theme (light or dark), but the GitHub icon at the top right corner is an SVG so it is always white, therefore it is almost invisible on the light theme.

Does this icon really need to be an SVG? 

If it doesn't then I could use a GitHub icon from the "react-icons/ai" library instead (like you did with the icons on the footer).

If it does then I can set a CSS property to fill it with the appropriate background color (like you did in the globals.css file).

Please let me know the solution you prefer

**Comment by kirandash** [comment]
@henriquebuzon Thanks for reporting this. Yes, there are few issues on the light theme. I didn't pay much attention to the light theme during development.

Please go ahead and use @react-icons/ai for the header icon as well. Since they are SVGs as well.

I will assign this task to you.

**Comment by henriquebuzon** [comment]
Did it!

**Comment by kirandash** [comment]
Thanks again 🙏🏻

**Comment by kirandash** [comment]
![image](https://github.com/bgwebagency/restoreportraits.com/assets/13310363/fdc77666-c555-4979-8eda-406781c1b509)

Deployed to Prod. Working Fine!
