### ISSUE TITLE
update readme file with a demo gif

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/restoreportraits.com#3]
Create a gif of the demo that shows image conversion

you can use the following image for the demo:

![1388704-watermark](https://github.com/bgwebagency/restoreportraits.com/assets/13310363/ea5c6fd4-fe2f-4dcb-8b52-3c200c09533f)

and add the final demo gif to the readme file.

**Comment by alexmk-97** [comment]
I would like to create the demo Gif :)
