### ISSUE TITLE
improve loading state with react loader spinner plugin

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/restoreportraits.com#6]
Plugin to use:

https://mhnpd.github.io/react-loader-spinner/docs/components/rotating-lines

Currently we have "loading" text in UploadComponent.tsx file

![image](https://github.com/bgwebagency/restoreportraits.com/assets/13310363/4a9d3a56-af6b-4679-a3b9-b8cc30d81bc7)

**To implement:** 

![image](https://github.com/bgwebagency/restoreportraits.com/assets/13310363/f43cb4b0-1056-4676-a970-5c0832c5e4cf)

**Comment by henriquebuzon** [comment]
I did it! I improved the loading state as you said.

However, I forgot to delete the .env file I created for testing purposes (sorry about that).

Please let me know if I did anything else wrong, this was my very first attempt to contribute to an open-source project.

Your project is really cool!

**Comment by kirandash** [comment]
@henriquebuzon Thanks a lot for your contribution! 🙏🏻

Here are a couple of my suggestions 💡 to help you with future open source contributions:

1. Before working on any issue, please comment on the issue asking for assignment. Ex, comment: "I would like to work on this". And if the project owner assigns you with the issue, it assures that your work will get reviewed. Otherwise someone else might also be working on the same issue and your effort will have a chance to get wasted

2. Regarding the .env file: you should read a bit more about how to uncommit sensitive data at: https://www.freecodecamp.org/news/how-to-uncommit-sensitive-files-from-git/

In this case, it was just a public key. So I didn't want to bother you much. But in future if you land with such problems: you should know how to not just delete the file. But also how to delete the change from git history. For security reasons. Because, although you deleted the file: I can still access your key from git history at: https://github.com/bgwebagency/restoreportraits.com/commit/60c3de07591572eec5396d0eb7b5d54a9644ecb1
So, you should learn how to remove it from git history as well.

I hope that helps. 

Feel free to look at my other open source projects. I have issues in few of them that might help you gain some more experience.

And, If you want to learn how I built this AI application, I have a complete in depth tutorial on how I built https://github.com/bgwebagency/redesigner.io at: https://youtu.be/4YXUGuo9OM4

Happy Coding! 👨🏻‍💻

**Comment by kirandash** [comment]
Deployed to Prod!

Working fine!

![image](https://github.com/bgwebagency/restoreportraits.com/assets/13310363/1551417a-6610-47d7-a705-7796ad2481b8)
