### ISSUE TITLE
add error notification if /restore API fails

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/restoreportraits.com#8]
Plugin to use: 

https://www.npmjs.com/package/react-notifications

**Comment by henriquebuzon** [comment]
Is everything okay with this library?

It seems to be deprecated. Their documentation still uses class components only.

I installed it by running "sudo npm install --save react-notifications" and then tried to import it with the statement: "import { NotificationManager} from 'react-notifications'" but then I got this error: "Could not find a declaration file for module 'react-notifications'."

Then I tried installing the types by running "npm i --save-dev @types/react-notifications" and got another error: "npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2freact-notifications - Not found"

One possible solution would be to use another library, such as "react-hot-toast". Would that be ok?

**Comment by kirandash** [comment]
> 

Hi @henriquebuzon 

yes, react-notifications isn't maintained actively. I think we can go with your suggestion of "react-hot-toast". 

"react-hot-toast" is very well maintained and also light weight compared to "react-toastify" or "react-notifications" and other competitors.
